Repository Manuel-Suarez-Abascal/translator-vuejs, pull requests merged in 2019-05, with the labels that each got.

#1 Added styling to the app & links
  README.md
  package-lock.json
  package.json
  src/components/Translator.vue
  src/main.js
Labels: enhancement

#2 Added languages selector to the app
  src/components/Translator.vue
Labels: enhancement

#4 Feature 1
  src/assets/langcodes.json
  src/components/LanguageSelector.vue
  src/components/Translator.vue
Labels: enhancement

#6 Fixed dark/light theme bug
  src/components/LanguageSelector.vue
  src/components/ThemeSwitcher.vue
  src/components/Translator.vue
Labels: bug

#7 Fix height background dark theme
  src/App.vue
  src/components/ThemeSwitcher.vue
Labels: bug

#8 Feature/add copy text btn
  package-lock.json
  package.json
  public/index.html
  src/components/Translator.vue
Labels: enhancement

#9 Fixed bug with tooltip in mobile version
  src/components/ThemeSwitcher.vue
  src/components/Translator.vue
Labels: bug

#10 Enhancement/preloader spinner animation
  src/App.vue
  src/components/Translator.vue
Labels: enhancement

#11 Fixed grid for different screen sizes of language selector component
  src/components/LanguageSelector.vue
Labels: enhancement

#12 Remove clipboard.js CDN and import it from json file
  deploy.sh
  public/index.html
  src/components/Translator.vue
  vue.config.js
Labels: enhancement

#13 Feature/language interchange
  public/index.html
  src/components/LanguageSelector.vue
Labels: enhancement

#14 Ordered json language options alphabetically
  src/assets/langcodes.json
Labels: enhancement

#15 fixed grid view in mobile version of theme switcher
  src/components/LanguageSelector.vue
Labels: bug, enhancement

#16 disabled btn for copying translation when translation is not available
  src/components/Translator.vue
Labels: enhancement

#17 Bug/fix tooltip
  src/components/Translator.vue
Labels: enhancement
